# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: ["feature/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # #if: startsWith(${{ github.event.pull_request.head.ref }}, "feature/")
    # if: ${{ startsWith(github.event.pull_request.head.ref, 'feature/') }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.event.pull_request.title}}
          if [[ "${{ github.event.pull_request.title}}" =~ [A-Za-z]{2,}-[0-9]+ ]]; then
            echo passes
          else
            echo fails
          fi
      - uses: KyoriPowered/action-regex-match@v3
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title}}
          regex: '[A-Za-z]{2,}-[0-9]+'

      - run: |
          echo ${{ steps.regex-match.outputs.match }}
          STATUS=$(curl --user ${{ secrets.JIRA_TOKEN }} "https://certifyos.atlassian.net/rest/api/2/issue/${{ steps.regex-match.outputs.match }}?fields=status" | jq -r '.fields.status.name')
          if [[ $STATUS == "Done" ]]; then
            echo "Done status"
          else
            echo "Status not done, failing"
            exit 1
          fi
        if: ${{ steps.regex-match.outputs.match != '' }}

      - run: echo hi
          
